[package]
name = "secret_store"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
base64 = "0.21.7"
chacha20poly1305 = "0.10.1"
clap = { version = "4.4.18", features = ["derive"] }
pbkdf2 = "0.12.2"
sha2 = "0.10.8"
text_io = "0.1.12"
