[package]
name = "secret_store"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive"] }
rusqlite = { version = "0.30.0", features = ["bundled-sqlcipher-vendored-openssl"] }
text_io = "0.1.12"
